// <auto-generated />
namespace GData.Ef6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class t2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t2));
        
        string IMigrationMetadata.Id
        {
            get { return "201710261035441_t2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
